name: nda2
channels:
- defaults
- conda-forge
dependencies:
- python=3.7.6
- pip
- mpi4py=3.0.3
- line_profiler=2.1.2
- tzlocal=1.5.1
- brian2=2.3.0.2
- pytables=3.5.2
- docopt=0.6.2
- dill=0.3.0
- numpy=1.17.2
- imbalanced-learn=0.5.0
- pandas=0.24.2
- h5py=2.10.0
- lmfit=0.9.14
- matplotlib=3.0.3
- psutil=5.6.3
- opencv=4.1.1
- umap-learn=0.3.9
- scipy=1.3.1
- patsy=0.5.1
- statsmodels=0.11.0
- joblib=0.13.2
- pyqtgraph=0.10.0
- quantities=0.12.3
- scikit-learn=0.20.0
- tabulate=0.8.3
- tqdm=4.36.1
- openpyxl=2.6.3
