#!/bin/bash

sbatch shellScripts/run_test_train_split_aligned_stim.sh
sbatch shellScripts/run_test_train_split_aligned_motion.sh
sbatch shellScripts/run_test_train_split_aligned_stim_covariances.sh
sbatch shellScripts/run_test_train_split_aligned_motion_covariances.sh