#!/bin/bash

sbatch shellScripts/run_plotter_aligned_perimovement_stim_lfp.sh
sbatch shellScripts/run_plotter_aligned_perimovement_stim_rig.sh
# sbatch shellScripts/run_plotter_aligned_perimovement_stim_neuron.sh